version: "3"
services:
    laravel:
        build:
            context: ./vendor/laravel/sail/runtimes/7.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: sail-8.0/app
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - mysql
            - redis
        ports:
            - "127.0.0.1:8081:80"
    nuxt:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "127.0.0.1:8080:3000"
        volumes:
            - ./client/:/app/
        env_file:
            - ./client/.env
        networks:
            - sail

    mysql:
        image: "mysql:8.0"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "sailmysql:/var/lib/mysql"
        networks:
            - sail
    redis:
        image: "redis:alpine"
        volumes:
            - "sailredis:/data"
        networks:
            - sail

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        networks:
            - sail
        ports:
            - 8082:80

networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
